#!/bin/sh
echo "$(figlet WOTH)"
echo " - Powered by Merriam-Webster, written by Amoghavarsha, @TheAmoghavarsha\n"

the_word() {
        echo "Please enter the date in %Y-%M-%D (2022-01-01) format"
        read enter
        curl -s https://www.merriam-webster.com/word-of-the-day/*$enter | grep -E "<title>" | sed 's/| Merriam-Webster//g' | sed 's/<title>//g' | sed 's/<\/title>//g' | sed 's/Word of the Day/Word of the Day/g' 
curl -s https://www.merriam-webster.com/word-of-the-day/*$enter | grep -E -m 5 "content=" | tail -n1 | sed 's/<meta name="description" content="//g' | sed 's/">//g' | sed 's/,">//g'

    }

while getopts ':o' OPTION; do
  case "$OPTION" in
    o) the_word ;;
   esac
   return
done


day=$(date "+%Y-%m-%d") 
curl -s https://www.merriam-webster.com/word-of-the-day/*$day  | grep -E "<title>" | sed 's/| Merriam-Webster//g' | sed 's/<title>//g' | sed 's/<\/title>//g' | sed 's/Word of the Day/Word of the Day/g' 
curl -s https://www.merriam-webster.com/word-of-the-day/*$day | grep -E -m 5 "content=" | tail -n1 | sed 's/<meta name="description" content="//g' | sed 's/">//g' | sed 's/,">//g'
 




